#!/bin/bash

cat > TEMPIN <<EOF
#
isrt harry quidditch
prta
prtt ----------------
blnk
#
isrt hermione magic
isrt ron chess
isrt hagrid dragon
prtt ----------------
blnk
prtk harry
prta
prtt ----------------
blnk
#
delt ron
prta
prtt ----------------
blnk
#
EOF

./p2 1 TEMPIN

